name: Dev CI

on:
  pull_request:
    branches:
      - '*'
      - '!main'
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    name: CI:build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '16'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build

  test:
    name: CI:test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '16'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
